@echo off
echo 此程序必须用管理员权限运行,并且关闭UAC,正在尝试自动设置权限......
reg.exe ADD HKLM\SOFTWARE\Microsoft\Windows\CurrentVersion\Policies\System /v EnableLUA /t REG_DWORD /d 0 /f
echo 设置成功,请重新启动系统后再次运行程序......
echo 按任意键退出......
pause